---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> All PLFA Data
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 15pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 8,
  fig.width = 9,
  class.source="bg-warning",
  class.output="bg-success"
)

```

# **Read in PLFA data**
```{r import_data}
PLFA_fun <- read.csv("Raw_data/PLFA/All_PLFA_fun.csv")
PLFA_bac <- read.csv("Raw_data/PLFA/All_PLFA_bac.csv")


```
# **Fungal Plot**
```{r plot_plfa_fungi}

# Fungi

library(ggplot2)

# re-label abbreviated veg
veg_types <- c(
  "M" = "Mesquite",
  "G" = "Grass", 
  "T" = "Mesquite-Grass"
)


library(dplyr)
#change order of variables so that the facet in the plot is in the best order
PLFA_fun <- PLFA_fun %>% mutate(Veg_abrev = factor(Veg_abrev, levels = c("G","T","M")))
#add a "Type" column so that the side facet label can be added in the final figure
PLFA_fun$Type<-"Fungi"

#plot fungal biomass
PLFA_plot_fun <- ggplot(PLFA_fun,
            aes(x=factor(Month, levels = c("October", "January", "March", "May", "July")),
                y = Total_Percent_Biomass))+
  geom_boxplot(show.legend = FALSE, aes(fill=Month))+
  facet_grid(Type~Veg_abrev, labeller = labeller(Veg_abrev = veg_types))+
 scale_y_continuous(labels = scales::percent_format(scale = 1), limits = c(0, 60))+ # change y-axis to percentage
  theme_linedraw()+
 theme(axis.title.x = element_blank(), axis.text.x = element_text(), axis.ticks.x   = element_blank(),
       axis.title.y = element_blank()) + 
  #ggtitle ("% of Fungi in Total Biomass Across Vegetation Types and Sampleing Periods")+  #change title
  theme( text = element_text(size = 12), axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
         strip.text.x = element_blank()) + 
  scale_fill_manual(values=c("October" ="#c1292e", "January" = "#e1bc29", "March" = "#679436", "May" = "#4895ef" , "July" ="#8187dc"), name = "Month") #add custom colors and change legend name

```

# **Bacterial Plot**
```{r plot_plfa_bacteria}

# Bacteria

library(ggplot2)

# re-label abbreviated veg
veg_types <- c(
  "M" = "Mesquite",
  "G" = "Grass", 
  "T" = "Grass-Mesquite"
)

library(dplyr)
#change order of variables so that the facet in the plot is in the best order
PLFA_bac <- PLFA_bac %>% mutate(Veg_abrev = factor(Veg_abrev, levels = c("G","T","M")))
#add a "Type" column so that the side facet label can be added in the final figure
PLFA_bac$Type<-"Bacteria"

#plot bacteria biomass
PLFA_plot_bac <- ggplot(PLFA_bac,
            aes(x=factor(Month, levels = c("October", "January", "March", "May", "July")),
                y = Total_Percent_Biomass))+
  geom_boxplot(show.legend = FALSE, aes(fill=Month))+
  facet_grid(Type~Veg_abrev, labeller = labeller(Veg_abrev = veg_types))+
 scale_y_continuous(labels = scales::percent_format(scale = 1))+ # change y-axis to percentage
  theme_linedraw()+
 theme(axis.title.x = element_blank(), axis.text.x = element_text(), axis.ticks.x   = element_blank(),
       axis.title.y = element_blank()) + 
  #ggtitle ("% of Bacteria in Total Biomass Across Vegetation Types and Sampleing Periods")+  #change title
  theme( text = element_text(size = 12), 
         axis.text.x = element_blank()) + 
  scale_fill_manual(values=c("October" ="#c1292e", "January" = "#e1bc29", "March" = "#679436", "May" = "#4895ef" , "July" ="#8187dc"), name = "Month") #add custom colors and change legend name



```


# **Fungal Stats**
```{r plfa_statistics_fungi}

# anova model of biomass by vegetation and month
  #month = month
  #vegetation = mesquite (M), grass (G), or mesquite_grass (T)
mod.plfa.fun <- aov(PLFA_fun$Total_Percent_Biomass ~ PLFA_fun$Month*PLFA_fun$Veg_abrev)

#check assumptions
par(mfrow = c(1,2)) #puts the plots next to each other
qqnorm(mod.plfa.fun$residuals) #normal q-q plot, tests normality
qqline(mod.plfa.fun$residuals, col = "red") #line of fit on q-q plot
plot(mod.plfa.fun$fitted.values, mod.plfa.fun$residuals, main = "Residuals vs Fitted", xlab = "Fitted Values", 
     ylab = "Residuals") #residuals vs. fitted, test variance
abline(h=0, col = "red") 

library(tidyverse)
library(dplyr)

#fungal data does not meet normallity assumptions, must log transform for anova
PLFA_fun2 <- read.csv("Raw_data/PLFA/All_PLFA_fun.csv")
PLFA_fun2$Total_Percent_Biomass<- log10(PLFA_fun2$Total_Percent_Biomass)
PLFA_fun2 <- PLFA_fun2 %>% 
  filter_at(vars(Total_Percent_Biomass), all_vars(!is.infinite(.)))



mod.plfa.fun2 <- aov(PLFA_fun2$Total_Percent_Biomass ~ PLFA_fun2$Month*PLFA_fun2$Veg_abrev)

#check assumptions
par(mfrow = c(1,2)) #puts the plots next to each other
qqnorm(mod.plfa.fun2 $residuals) #normal q-q plot, tests normality
qqline(mod.plfa.fun2 $residuals, col = "red") #line of fit on q-q plot
plot(mod.plfa.fun2 $fitted.values, mod.plfa.fun2 $residuals, main = "Residuals vs Fitted", xlab = "Fitted Values", 
     ylab = "Residuals") #residuals vs. fitted, test variance
abline(h=0, col = "red") 



#summary of anova results
summary(mod.plfa.fun2)

#Post hoc analysis of anova
tuk.plfa.fun2 <- TukeyHSD(mod.plfa.fun2)

#tukeyHSD pairwise vegetation results based on ANOVA model  
tuk.plfa.fun2$`PLFA_fun2$Veg_abrev`

library(dplyr)
library(tibble)
library(utils)
library(tidyverse)

# convert tukey results to dataframe
x.fun <- as.data.frame(tuk.plfa.fun2$`PLFA_fun2$Month:PLFA_fun2$Veg_abrev`) 

# get a column with the comparison labels
y.fun <- tibble::rownames_to_column(x.fun, "label")


#isolate comparisons that are relevant
G_fun <- dplyr::filter(y.fun, grepl("^.*:G.*:G", label))
M_fun <- dplyr::filter(y.fun, grepl("^.*:M.*:M", label)) 
T_fun <- dplyr::filter(y.fun, grepl("^.*:T.*:T", label)) 


# merge fungal data
fun <- G_fun %>%
  full_join(M_fun, by = c("label", "diff", "lwr", "upr", "p adj")) 

fun <- fun %>%
  full_join(T_fun, by = c("label", "diff", "lwr", "upr", "p adj"))

#filter for significant values
fun_signif <- fun %>%
filter(fun$`p adj` < .05) 

#view signif
fun_signif


```

# **Bacterial Stats**
```{r plfa_statistics_bacterial}


# anova model of biomass by vegetation and month
  #month = month
  #vegetation = mesquite (M), grass (G), or mesquite_grass (T)
mod.plfa.bac <- aov(PLFA_bac$Total_Percent_Biomass ~ PLFA_bac$Month*PLFA_bac$Veg_abrev)

#summary of anova results
summary(mod.plfa.bac)


#check anova assumptions

par(mfrow = c(1,2)) #puts the plots next to each other
qqnorm(mod.plfa.bac$residuals) #normal q-q plot, tests normality
qqline(mod.plfa.bac$residuals, col = "red") #line of fit on q-q plot
plot(mod.plfa.bac$fitted.values, mod.plfa.bac$residuals, main = "Residuals vs Fitted", xlab = "Fitted Values", 
     ylab = "Residuals") #residuals vs. fitted, test variance
abline(h=0, col = "red") 




#Post hoc analysis of anova
tuk.plfa.bac <- TukeyHSD(mod.plfa.bac)

#tukeyHSD pairwise vegetation results based on ANOVA model
tuk.plfa.bac$`PLFA_bac$Veg_abrev`

library(dplyr)
library(tibble)
library(utils)
library(tidyverse)

# convert tukey results to dataframe
x.bac <- as.data.frame(tuk.plfa.bac$`PLFA_bac$Month:PLFA_bac$Veg_abrev`) 

# get a column with the comparison labels
y.bac <- tibble::rownames_to_column(x.bac, "label")


#isolate comparisons that are relevant
G_bac <- dplyr::filter(y.bac, grepl("^.*:G.*:G", label))
M_bac <- dplyr::filter(y.bac, grepl("^.*:M.*:M", label)) 
T_bac <- dplyr::filter(y.bac, grepl("^.*:T.*:T", label)) 


# merge fungal data
bac <- G_bac %>%
  full_join(M_bac, by = c("label", "diff", "lwr", "upr", "p adj")) 

bac <- bac %>%
  full_join(T_bac, by = c("label", "diff", "lwr", "upr", "p adj"))

#filter for significant values
bac_signif <- bac %>%
filter(bac$`p adj` < .05) 

#view signif
bac_signif

```
# **Manually Set Fungal p-values**
- https://csdaw.github.io/ggprism/articles/pvalues.html
```{r fun_signif_plot}

library(ggprism)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(rstatix)


# make tukey hsd dataframe with rstatix package
stat.test.fun <- aov(Total_Percent_Biomass ~ Month*Veg_abrev, data = PLFA_fun2) %>%
  tukey_hsd()

# add column with complete tukey comparison
stat.test.fun$full_compar = paste(stat.test.fun$group1, stat.test.fun$group2, sep="-")

# filter out everything not looking at vegetation:month
stat.fun <- dplyr::filter(stat.test.fun, grepl("Month:Veg_abrev", term))


#isolate comparisons that are relevant
G_fun_stat <- dplyr::filter(stat.fun, grepl("^.*:G.*:G", full_compar))
M_fun_stat <- dplyr::filter(stat.fun, grepl("^.*:M.*:M", full_compar))
T_fun_stat <- dplyr::filter(stat.fun, grepl("^.*:T.*:T", full_compar)) 

# merge relevant comparisons to one dataframe
fun_stat <- G_fun_stat %>%
  full_join(M_fun_stat, by = c("term", "group1", "group2", "null.value", "estimate", "conf.low", "conf.high", "p.adj", "p.adj.signif", "full_compar")) 

fun_stat <- fun_stat %>%
  full_join(T_fun_stat, by = c("term", "group1", "group2", "null.value", "estimate", "conf.low", "conf.high", "p.adj", "p.adj.signif", "full_compar")) 

# make a column with only Veg_abrev so that this data set matches with the PLFA data
fun_stat <- separate(data = fun_stat, col = group1, into = c("group1", "Veg_abrev"), sep = "\\:")

#remove vegetation abbreviation from group2
fun_stat$group2<- gsub(':G','',fun_stat$group2)
fun_stat$group2<- gsub(':M','',fun_stat$group2)
fun_stat$group2<- gsub(':T','',fun_stat$group2)


#filter out non significant values
fun_stat <- fun_stat %>%
filter(fun_stat$p.adj < .05) 


library(dplyr)

# select only the necessary columns from the data frame 
grouped_for_plot_fun <- fun_stat %>%
  select(group1, group2, p.adj, p.adj.signif, Veg_abrev) %>%
   mutate(Veg_abrev = factor(Veg_abrev, levels = c("G","T","M"))) %>%
  as.tibble()
  

# manually add y-position for each p-value
grouped_for_plot_fun <- grouped_for_plot_fun %>%
  add_column(y.position = c(40, 35, 30, 50, 25, 45,
                            40, 35, 30, 25, 45, 
                            40, 35, 30, 50, 25, 45))



# merge the p-values with the plot
fun_with_p <- PLFA_plot_fun +  add_pvalue(grouped_for_plot_fun) 


```

# **Manually Set Bacterial p-values**
```{r bac_signif_plot}

library(ggprism)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(rstatix)


# make tukey hsd dataframe with rstatix package
stat.test.bac <- aov(Total_Percent_Biomass ~ Month*Veg_abrev, data = PLFA_bac) %>%
  tukey_hsd()

# add column with complete tukey comparison
stat.test.bac$full_compar = paste(stat.test.bac$group1, stat.test.bac$group2, sep="-")

# filter out everything not looking at vegtation:month
stat.bac <- dplyr::filter(stat.test.bac, grepl("Month:Veg_abrev", term))


#isolate comparisons that are relevant
G_bac_stat <- dplyr::filter(stat.bac, grepl("^.*:G.*:G", full_compar))
M_bac_stat <- dplyr::filter(stat.bac, grepl("^.*:M.*:M", full_compar))
T_bac_stat <- dplyr::filter(stat.bac, grepl("^.*:T.*:T", full_compar)) 

# merge relevant comparisons to one datafram
bac_stat <- G_bac_stat %>%
  full_join(M_bac_stat, by = c("term", "group1", "group2", "null.value", "estimate", "conf.low", "conf.high", "p.adj", "p.adj.signif", "full_compar")) 

bac_stat <- bac_stat %>%
  full_join(T_bac_stat, by = c("term", "group1", "group2", "null.value", "estimate", "conf.low", "conf.high", "p.adj", "p.adj.signif", "full_compar")) 

# make a column with only Veg_abrev so that this dataset matches with the PLFA data
bac_stat <- separate(data = bac_stat, col = group1, into = c("group1", "Veg_abrev"), sep = "\\:")

#remove vegetation abbreviation from group2
bac_stat$group2<- gsub(':G','',bac_stat$group2)
bac_stat$group2<- gsub(':M','',bac_stat$group2)
bac_stat$group2<- gsub(':T','',bac_stat$group2)


#filter out non significant values
bac_stat <- bac_stat %>%
filter(bac_stat$p.adj < .05) 


library(dplyr)

# select only the necessary columns from the dataframe and factor Veg_abrev so that the order is correct in the plot
grouped_for_plot_bac <- bac_stat %>%
  select(group1, group2, p.adj, p.adj.signif, Veg_abrev) %>%
  mutate(Veg_abrev = factor(Veg_abrev, levels = c("G","T","M"))) %>%
  as.tibble()
  
#manually add y-position for each p-value
grouped_for_plot_bac <- grouped_for_plot_bac %>%
  add_column(y.position = c(55, 51, 46, 62, 43, 59, 
                            54, 50, 46, 62, 43, 59,
                            53, 45, 49, 38, 62, 33, 56, 59))


# merge the p-values with the plot
bac_with_p <- PLFA_plot_bac +  add_pvalue(grouped_for_plot_bac)

```

# **Compile Plots**
```{r}

library(ggpubr)

figure <- ggarrange(bac_with_p, fun_with_p, 
          ncol = 1, nrow = 2)

final <- annotate_figure(figure,
              top = text_grob("Percentage of Bacterial and Fungal Biomass Across Vegetation Types and Sampling Periods", color = "black", face = "bold", size = 12),
               left = text_grob("% of Total Microbial Biomass", color = "black", rot = 90)
              )

final

#library(svglite)
#ggsave(file="PLFA_all_ggarrange.svg", plot=final, width=9, height=9)

```