---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Bacteria Mixed Effects Models
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 12pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 4,
  fig.width = 6,
  class.source="bg-warning",
  class.output="bg-success"
)

```


```{r import_data}

library(phyloseq)
library(dplyr)
library(tidyverse)
library(vegan)


load("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/bacteria_dada2_data.RData") 
#contains taxa and otu table


#import metadata
sam <- read.csv("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/Bacteria/dada2_files/nov_2_metadata.csv", header = TRUE) 
rownames(sam) <- sam$sample.id

#add month_veg row to data
sam$month_veg = paste(sam$month, sam$vegetation, sep="-")

#adjust sample data labels
sam$Vegetation <- factor(sam$vegetation, levels = c("Grass", "Mesquite_grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 

sam$Month <- factor(sam$month, levels = c("Oct", "Jan", "Mar", "May", "Jul"), 
                  labels = c("October", "January", "March", "May", "July"))

#compile data into phyloseq object
phylo_raw <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), 
               sample_data(sam), 
               tax_table(taxa))


dna <- Biostrings::DNAStringSet(taxa_names(phylo_raw))
names(dna) <- taxa_names(phylo_raw)
phylo_raw <- merge_phyloseq(phylo_raw, dna)
taxa_names(phylo_raw) <- paste0("ASV", seq(ntaxa(phylo_raw)))
phylo_raw

#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```
# **remove controls + contaminants**

```{r decontam}
library(decontam)

# threshold 0.5, identifies 6 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)

#prune the contaminated taxa
phylo_rm_contaminat <- prune_taxa(!contamdf.prev05$contaminant, phylo_raw)
phylo_rm_contaminat #after

#remove any left over controls 
phylo_rm_contaminat_rm_cntrl = subset_samples(phylo_rm_contaminat, sample.id != "CONTROL1" & sample.id != "CONTROL2" & sample.id != "CONTROL3" & sample.id != 129)


## remove unknowns and archaea, keep only bacteria
bac <- subset_taxa(phylo_rm_contaminat_rm_cntrl, Kingdom == "Bacteria")
phylo_rm_archaea <- prune_taxa(c(taxa_names(bac)), phylo_rm_contaminat_rm_cntrl) 
phylo_rm_archaea 

```

# **Use phyloseq object for linear model**

What models do I want to run? 

  - bac biomass x pH
  - bac biomass x C:N
  - bac biomass x air temp
  - bac biomass x humidity
  - bac biomass x precip

```{r}
library(microbiome)
library(ggplot2)
library(dplyr)
library(IRanges)

# Get sample metadata
dfs <- meta(phylo_rm_archaea)

library(lme4)
library(lmerTest)
library(sjPlot)
# Paired comparison
out1 <- lmer(bacterial_biomass_percentage ~ soil_pH + (1| plot), data = dfs)
tab_model(out1)



out2 <- lmer(bacterial_biomass_percentage ~ carbon_to_nitrogen_ratio + (1| plot), data = dfs)
AIC(out2) #1039.51
tab_model(out2)

out3 <- lmer(bacterial_biomass_percentage ~ avg_monthly_air_temp_C + (1| plot), data = dfs)
AIC(out3) #964.2789
tab_model(out3)



out4 <- lmer(bacterial_biomass_percentage ~ average_montlhy_humidity + (1| plot), data = dfs)
AIC(out4) #981.3405
tab_model(out4)


out5 <- lmer(bacterial_biomass_percentage ~ avg_monthly_ppt + (1| plot), data = dfs)
AIC(out5) #1045.317
tab_model(out5)


out6 <- lmer(bacterial_biomass_percentage ~ average_montlhy_humidity*avg_monthly_air_temp_C + (1| plot), data = dfs)
tab_model(out6)

out7 <- lmer(bacterial_biomass_percentage ~ average_montlhy_humidity + avg_monthly_air_temp_C + soil_pH + (1| plot), data = dfs)
tab_model(out7)

out8 <- lmer(bacterial_biomass_percentage ~ average_montlhy_humidity + avg_monthly_air_temp_C + soil_pH + carbon_to_nitrogen_ratio + (1| plot), data = dfs)
tab_model(out8)



### model 6 seems to be the best, need to check assumptions ###
plot(out6)
qqnorm(resid(out6))
qqline(resid(out6), col = "red") 


#assumptions not met, need to transform

out6_log <- lmer(log(bacterial_biomass_percentage) ~ (average_montlhy_humidity)* (avg_monthly_air_temp_C) + (1| plot), data = dfs)
tab_model(out6_log)

plot(out6_log)
qqnorm(resid(out6_log))
qqline(resid(out6_log), col = "red") 

```



```{r}
library(tidyverse) # data manipulation and ggplot 
library(janitor) # data cleaning 
library(magrittr)  # data manipulation 
library(reshape2) # data manipulation 
library(phyloseq) # output format of sequence processing 
library(microbiome) # useful exploration and visualisation functions 
library(MCMCglmm) # implementation of GLMMs 
library(ALDEx2) # CLR transformations
library(plotrix) # std error functions 
library(pals) # palettes 
library(MetBrewer) # palettes 
library(ggregplot) # package my friend made with lots of handy funcions - 


summarize_phyloseq(phylo_rm_archaea) 

 
psPhy <- tax_glom(phylo_rm_archaea, taxrank = "Order") # aggregates to the order level 
psMelt <- psmelt(psPhy) # melts into a combined df for plots 


out_mem1 <- lmer(Abundance ~ soil_pH + (1| plot) , data = psMelt)
tab_model(out_mem1)

out_mem2 <- lmer(Abundance ~ carbon_to_nitrogen_ratio + (1| plot) , data = psMelt)
tab_model(out_mem2)

out_mem3 <- lmer(Abundance ~ average_montlhy_humidity + (1| plot) , data = psMelt)
tab_model(out_mem3)

out_mem4 <- lmer(Abundance ~ avg_monthly_air_temp_C + (1| plot) , data = psMelt)
tab_model(out_mem4)

out_mem5 <- lmer(Abundance ~ bacterial_biomass_percentage + (1| plot) , data = psMelt)
tab_model(out_mem5)

out_mem6 <- lmer(Abundance ~ Vegetation + (1| plot) , data = psMelt)
tab_model(out_mem6)

out_mem7 <- lmer(Abundance ~ month + (1| plot) , data = psMelt)
tab_model(out_mem7)
```
 
 