---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Bacteria Richness and Diversity
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 12pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 4,
  fig.width = 6,
  class.source="bg-warning",
  class.output="bg-success"
)

```



# Reasons

- This paper (https://doi.org/10.3390%2Fplants8110479) found significance when looking at microbial richness and diversity

- alpha diversity with shannon looks at species eveness + richness (https://doi.org/10.4014/jmb.1709.09027)

- but to look at richness I can use ACE (https://doi.org/10.4014/jmb.1709.09027)


# import data:
```{r import_data}

library(phyloseq)
library(dplyr)
library(tidyverse)
library(vegan)


load("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/bacteria_dada2_data.RData") 
#contains taxa and otu table


#import metadata
sam <- read.csv("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/Bacteria/dada2_files/nov_2_metadata.csv", header = TRUE) 
rownames(sam) <- sam$sample.id

#add month_veg row to data
sam$month_veg = paste(sam$month, sam$vegetation, sep="-")

#adjust sample data labels
sam$Vegetation <- factor(sam$vegetation, levels = c("Grass", "Mesquite_grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 

sam$Month <- factor(sam$month, levels = c("Oct", "Jan", "Mar", "May", "Jul"), 
                  labels = c("October", "January", "March", "May", "July"))

#compile data into phyloseq object
phylo_raw <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), 
               sample_data(sam), 
               tax_table(taxa))


dna <- Biostrings::DNAStringSet(taxa_names(phylo_raw))
names(dna) <- taxa_names(phylo_raw)
phylo_raw <- merge_phyloseq(phylo_raw, dna)
taxa_names(phylo_raw) <- paste0("ASV", seq(ntaxa(phylo_raw)))
phylo_raw

#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```

# **remove controls + contaminants**

```{r decontam}
library(decontam)

# threshold 0.5, identifies 6 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)

#prune the contaminated taxa
phylo_rm_contaminat <- prune_taxa(!contamdf.prev05$contaminant, phylo_raw)
phylo_rm_contaminat #after

#remove any left over controls so they don't impact rarefy
#remove sample 129 and 93 as it had very low reads after filtering, don't want them to impact rarefy
phylo_rm_contaminat_rm_cntrl = subset_samples(phylo_rm_contaminat, sample.id != "CONTROL1" & sample.id != "CONTROL2" & sample.id != "CONTROL3" & sample.id != 129 & sample.id != 93)


## remove unknowns and archaea, keep only bacteria
bac <- subset_taxa(phylo_rm_contaminat_rm_cntrl, Kingdom == "Bacteria")
phylo_rm_archaea <- prune_taxa(c(taxa_names(bac)), phylo_rm_contaminat_rm_cntrl) 
phylo_rm_archaea 

```


```{r richness}
richness <- estimate_richness(phylo_rm_archaea)

#Shannon
anova.sh.veg = aov(richness$ACE ~ sample_data(phylo_rm_archaea)$Vegetation*sample_data(phylo_rm_archaea)$Month)
summary(anova.sh.veg)

#post hoc
tukey.sh <- TukeyHSD(anova.sh.veg)
tukey.sh$`sample_data(phylo_rm_archaea)$Month`

tukey.sh 


#plot
ACE <- plot_richness(phylo_rm_archaea, x = "Month", measures = c("ACE"))
ACE_box <- ACE + geom_boxplot()
ACE_box

```



```{r phylogenic_diversity}

library(picante)
otu_table <- as.data.frame(phylo_rm_archaea@otu_table)
metadata_table <- as.data.frame(phylo_rm_archaea@sam_data)

df.pd <- pd(t(otu_table), treefile_p1, include.root=F) # t(ou_table) transposes the table for use in picante and the tre file comes from the first code chunck we used to read tree file (see making a phyloseq object section).


datatable(df.pd)

```