---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Bacterial Indicator Species
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 15pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 6,
  fig.width = 9,
  class.source="bg-warning",
  class.output="bg-success"
)

```


# **Import qiime formatted data**
  - https://blog.codyglickman.com/2018/10/qiime2-to-phyloseq.html

```{r import_data}
library(phyloseq)

biom_data_raw <- import_biom(BIOMfilename = "Bacteria/bacteria_taxa_table_raw.biom", refseqfilename = "Bacteria/bacteria-dna-sequences-rare.fasta")

mapping_file <- import_qiime_sample_data(mapfilename = "Bacteria/CORRECTED_metadata.tsv")


# Merge the OTU and mapping data into a phyloseq object
phylo_raw <- merge_phyloseq(biom_data_raw, mapping_file)
#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```
# **remove controls + contaminants**

```{r clean_data}
library(decontam)

# threshold 0.5, identifies 9 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)

#prune the contaminated taxa
phylo_rm_contaminat <- prune_taxa(!contamdf.prev05$contaminant, phylo_raw)
phylo_rm_contaminat #after

#remove any left over controls so they dont impact normalization
phylo_rm_contaminat_rm_cntrl = subset_samples(phylo_rm_contaminat, sample.id != "CONTROL1-S1" & sample.id != "CONTROL2-S79" & sample.id != "CONTROL3-S109")


## remove unknowns and archaea, keep only bacteria
bac <- subset_taxa(phylo_rm_contaminat_rm_cntrl, Kingdom == "d__Bacteria")
phylo_rm_archaea <- prune_taxa(c(taxa_names(bac)), phylo_rm_contaminat_rm_cntrl) 

```
#**Isolate ASV table from phyloseq**
```{r}
library(tibble)
library(dplyr)

#relative abundance
phylo_rm_archaea  = transform_sample_counts(phylo_rm_archaea, function(x) x / sum(x) )
phylo_rm_archaea = filter_taxa(phylo_rm_archaea, function(x) sd(x)/mean(x) > 3.0, TRUE)

# Extract abundance matrix from the phyloseq object
OTU1 = as(otu_table(phylo_rm_archaea), "matrix")
# transpose if necessary
if(taxa_are_rows(phylo_rm_archaea)){OTU1 <- t(OTU1)}
# Coerce to data.frame
OTUdf = as.data.frame(OTU1)



#extract taxa table
taxa = as(tax_table(phylo_rm_archaea), "matrix")
taxadf = as.data.frame(taxa)
taxadf <- tibble::rownames_to_column(taxadf, "sample.id")

# transpose 


#add metadata to OTU table
metadata <- read.csv("Bacteria/CORRECTED_metadata.csv")
metadata$month_veg = paste(metadata$month, metadata$megetation, sep="-")

OTUdf2 <- tibble::rownames_to_column(OTUdf, "sample.id")
OTUdf_merge <- merge(metadata, OTUdf2, by.y= "sample.id")


#merge taxa table with otu table
OTU1 = as(otu_table(phylo_rm_archaea), "matrix")
OTU1 = as.data.frame(OTU1)
OTU1 <- tibble::rownames_to_column(OTU1, "sample.id")

OTU_taxa_merge <- merge(OTU1, taxadf, by.y= "sample.id")
```


- https://uw.pressbooks.pub/appliedmultivariatestatistics/chapter/isa/
- https://cran.r-project.org/web/packages/indicspecies/vignettes/IndicatorSpeciesAnalysis.html#additional-functions-to-estimate-and-test-the-association-between-species-and-groups-of-sites 

```{r}
library(indicspecies)

##### indicator species grouped by vegetation ####

bac.veg.ISA <- multipatt(x = OTUdf,
cluster = OTUdf_merge$vegetation,
duleg = TRUE, control = how(nperm=999))

summary(bac.veg.ISA)


#convert to data frame with sample id column
indisp_veg <- as.data.frame(bac.veg.ISA$sign, keep.rownames = TRUE)
indisp_veg <- tibble::rownames_to_column(indisp_veg, "sample.id")


#merge taxa table with significant indicator species
indisp_veg_taxa <- merge(OTU_taxa_merge, indisp_veg, by.y= "sample.id")

#filter out non significant values
library(dplyr)
indisp_veg_taxa <- indisp_veg_taxa %>%
filter(indisp_veg_taxa$p.value < .05) 


##### indicator species grouped by month ####

bac.month.ISA <- multipatt(x = OTUdf,
cluster = OTUdf_merge$month,
duleg = TRUE, control = how(nperm=999))

summary(bac.month.ISA)


#convert to data frame with sample id column
indisp_month <- as.data.frame(bac.month.ISA$sign, keep.rownames = TRUE)
indisp_month <- tibble::rownames_to_column(indisp_month, "sample.id")


#merge taxa table with significant indicator species
indisp_month_taxa <- merge(OTU_taxa_merge, indisp_month, by.y= "sample.id")

#filter out non significant values
library(dplyr)
indisp_month_taxa <- indisp_month_taxa %>%
filter(indisp_month_taxa$p.value < .05) 



##### indicator species grouped by month and vegetation ####

bac.month.veg.ISA <- multipatt(x = OTUdf,
cluster = OTUdf_merge$month_veg,
duleg = TRUE, control = how(nperm=999))

summary(bac.month.veg.ISA)


#filter out non significant values
indisp_month_veg <- as.data.frame(bac.month.veg.ISA$sign, keep.rownames = TRUE)
indisp_month_veg <- tibble::rownames_to_column(indisp_month_veg, "sample.id")


#merge taxa table with significant indicator species
indisp_month_veg_taxa <- merge(OTU_taxa_merge, indisp_month_veg, by.y= "sample.id")

#filter out non significant values
library(dplyr)
indisp_month_veg_taxa <- indisp_month_veg_taxa %>%
filter(indisp_month_veg_taxa$p.value < .05) 
```

```{r}
#make new phyloseq object with only indicator species

tax_veg = indisp_veg_taxa[,c(1, 136:139)]

tax_veg <- tax_veg %>%
    tibble::column_to_rownames("sample.id")

tax_veg <- as.matrix(tax_veg)

otu_veg = indisp_veg_taxa[,c(1:135)]

otu_veg <- otu_veg %>%
    tibble::column_to_rownames("sample.id")

sam = mapping_file


  OTU = otu_table(otu_veg, taxa_are_rows = TRUE)
  TAX = tax_table(tax_veg)
  samples = sample_data(sam)

indic_veg_phylo <- phyloseq(OTU, TAX, samples)

```

