---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Bacteria Decontam
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 12pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 4,
  fig.width = 6,
  class.source="bg-warning",
  class.output="bg-success"
)

```

# **import data**
```{r}
library(phyloseq)

biom_data_raw <- import_biom(BIOMfilename = "Bacteria/bacteria_taxa_table_raw.biom", refseqfilename = "Bacteria/bacteria-dna-sequences-rare.fasta")

mapping_file <- import_qiime_sample_data(mapfilename = "Bacteria/CORRECTED_metadata.tsv")



# Merge the OTU and mapping data into a phyloseq object
phylo_raw <- merge_phyloseq(biom_data_raw, mapping_file)
#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")

```

# **filter controls with decontam**
  - https://doi.org/10.1128%2FmSystems.00290-19
  - following tis tutorial: https://benjjneb.github.io/decontam/vignettes/decontam_intro.html 
  
  
```{r}
library(decontam)

#inspect library size

library(ggplot2)
df <- as.data.frame(sample_data(phylo_raw)) # Put sample_data into a ggplot-friendly data.frame
df$LibrarySize <- sample_sums(phylo_raw)
df <- df[order(df$LibrarySize),]
df$Index <- seq(nrow(df))
ggplot(data=df, aes(x=Index, y=LibrarySize, color=Sample_or_Control)) + geom_point()

#identify contaminant prevalence

#default threshold, identifies 5 contaminants
contamdf.prev <- isContaminant(phylo_raw, method="prevalence", neg="neg")
table(contamdf.prev$contaminant)

# threshold 0.5, identifies 9 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)


# Make phyloseq object of presence-absence in negative controls and true samples
ps.pa <- transform_sample_counts(phylo_raw, function(abund) 1*(abund>0))
ps.pa.neg <- prune_samples(sample_data(ps.pa)$Sample_or_Control == "Control", ps.pa)
ps.pa.pos <- prune_samples(sample_data(ps.pa)$Sample_or_Control == "Sample", ps.pa)
# Make data.frame of prevalence in positive and negative samples
df.pa <- data.frame(pa.pos=taxa_sums(ps.pa.pos), pa.neg=taxa_sums(ps.pa.neg),
                      contaminant=contamdf.prev$contaminant)
ggplot(data=df.pa, aes(x=pa.neg, y=pa.pos, color=contaminant)) + geom_point(position = "jitter") +
  xlab("Prevalence (Negative Controls)") + ylab("Prevalence (True Samples)")

```


# **prune contaminants**
- https://rpubs.com/microbiotic/833244

```{r}
library(tidyverse)
library(DT)

row_indices <- which(contamdf.prev05$contaminant) #grab the row indices that correspond with identified contaminants to locate taxonomic information in the corresponding OTU file

taxonomy_table <- tibble()

df.taxa <- as.data.frame(tax_table(phylo_raw))
classification <- c("kingdom", "phylum", "class", "order", "family", "genus", "species")

for (i in row_indices){
  loc <-  contamdf.prev05[i, 0]
  tax_key <- row.names(loc)
  tax_value <- df.taxa[tax_key, ]
  taxonomy_table <- rbind(taxonomy_table, tax_value)
}

names(taxonomy_table) <- classification
#datatable(taxonomy_table)


phylo_raw #before
#phyloseq-class experiment-level object
#otu_table()   OTU Table:         [ 26045 taxa and 137 samples ]
#sample_data() Sample Data:       [ 137 samples by 6 sample variables ]
#tax_table()   Taxonomy Table:    [ 26045 taxa by 7 taxonomic ranks ]
#refseq()      DNAStringSet:      [ 26045 reference sequences ]

#prune the contaminated taxa
biom_rm_contaminat <- prune_taxa(!contamdf.prev05$contaminant, phylo_raw)
biom_rm_contaminat #after

#phyloseq-class experiment-level object
#otu_table()   OTU Table:         [ 26036 taxa and 137 samples ]
#sample_data() Sample Data:       [ 137 samples by 6 sample variables ]
#tax_table()   Taxonomy Table:    [ 26036 taxa by 7 taxonomic ranks ]
#refseq()      DNAStringSet:      [ 26036 reference sequences ]

```