---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Carbon to Nitrogen
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 15pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 6,
  fig.width = 9,
  class.source="bg-warning",
  class.output="bg-success"
)

```


```{r import_data}

metadata <- read.csv("Bacteria/CORRECTED_metadata.csv", header = TRUE)

library(dtplyr)
library(tidyverse)
#remove controls to remove NAs
metadata <- metadata %>% drop_na()

#re label 
metadata$vegetation <- factor(metadata$vegetation, levels = c("Grass", "Mesquite_grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 

metadata$month <- factor(metadata$month, levels = c("Oct", "Jan", "Mar", "May", "Jul"), 
                  labels = c("October", "January", "March", "May", "July"))

metadata$veg_abrev <- factor(metadata$vegetation, levels = c("Grass", "Grass-Mesquite", "Mesquite"), 
                  labels = c("M", "T", "G"))

```


```{r write_plots}

#plot C:N ratio
library(ggplot2)

CN_plot <- ggplot(metadata, aes(x=month, #change order of x-axis
                          y=carbon_to_nitrogen_ratio))+
  geom_boxplot(show.legend = FALSE, aes(fill = month))+
  theme_linedraw()+
  theme(plot.title = element_text(face = "bold", hjust = 0.5),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        axis.title.x = element_blank())+
  facet_wrap(~vegetation)+
  stat_summary(fun.y=mean, geom="point", shape=23, color="red", fill="yellow") +
  xlab("Vegetation") + # change x axis label
  ylab("Carbon to Nitrogen")+ # change y axis label
  scale_fill_manual(values=c("October" ="#c1292e", "January" = "#e1bc29", "March" = "#679436", "May" = "#4895ef" , "July" ="#8187dc"), name = "month")+
  ggtitle("Carbon to Nitrogen Ratio: Seasonal Variation")


CN_plot_veg <- ggplot(metadata, aes(x=vegetation, #change order of x-axis
                          y=carbon_to_nitrogen_ratio))+
  geom_boxplot(show.legend = FALSE, aes(fill = vegetation))+
  theme_linedraw()+
  theme(plot.title = element_text(face = "bold", hjust = 0.5) )+
  stat_summary(fun.y=mean, geom="point", shape=23, color="red", fill="yellow") +
  xlab("Vegetation") + # change x axis label
  ylab("Carbon to Nitrogen")+ # change y axis label
 scale_fill_manual(values=c("Mesquite" ="#c1292e", "Grass-Mesquite" = "#e1bc29", "Grass" = "#679436"))+
  ggtitle("Carbon to Nitrogen Ratio: Vegatation Variation")

```


#**Carbon:Nitrogen Stats**

```{r stat_tests}
#anova of C:N by month/vegetation
cn_aov <- aov(carbon_to_nitrogen_ratio ~ month*vegetation, data = metadata)
summary(cn_aov)

#check anova assumptions
par(mfrow = c(1,2)) #puts the plots next to each other
qqnorm(cn_aov$residuals) #normal q-q plot, tests normality
qqline(cn_aov$residuals, col = "red") #line of fit on q-q plot
plot(cn_aov$fitted.values, cn_aov$residuals, main = "Residuals vs Fitted", xlab = "Fitted Values", 
     ylab = "Residuals") #residuals vs. fitted, test variance
abline(h=0, col = "red") 


#tukey post hoc of anova
cn_tuk <- TukeyHSD(cn_aov)

#view significant pairwise tukey comparisons 

  #vegetation
tuk_cn_veg <- as.data.frame(cn_tuk$vegetation)

tuk_cn_veg %>%
filter(`p adj` < .05) 

  #month
tuk_cn_month <- as.data.frame(cn_tuk$month)

tuk_cn_month%>%
filter(`p adj` < .05)

  #month:vegetation
tuk_cn_veg_month <- as.data.frame(cn_tuk$`month:vegetation`)

tuk_cn_veg_month_signif <- tuk_cn_veg_month %>%
filter(`p adj` < .05)

```

```{r add_p_values}

#add P values
library(ggpubr)
library(tidyverse)
library(rstatix)


#### for vegetation plot ####
#tukeyhsd data frame
CN_stat <- aov(carbon_to_nitrogen_ratio ~ month*vegetation, data = metadata) %>%
      tukey_hsd() 

#filter to only desired comparisons
CN_stat_veg <- dplyr::filter(CN_stat, grepl("^vegetation", term))

# manually add y position
CN_stat_veg <- CN_stat_veg %>%
 mutate(y.position = c(13, 14, 12))

# add p-values to plot
CN_plot_veg + stat_pvalue_manual(CN_stat_veg , label = "p.adj.signif", hide.ns = TRUE)




#### for faceted plot ####
#tukeyhsd data frame
CN_stat <- aov(carbon_to_nitrogen_ratio ~ month*veg_abrev, data = metadata) %>%
      tukey_hsd() 

CN_stat <- CN_stat %>%
filter(`p.adj` < .05)

#filter to only desired comparisons
CN_stat_veg_month <- dplyr::filter(CN_stat, grepl("^month:veg_abrev", term))

# add column with complete tukey comparison
CN_stat_veg_month$full_compar = paste(CN_stat_veg_month$group1, CN_stat_veg_month$group2, sep="-")

#isolate comparisons that are relevant
G_CN_stat_veg_month <- dplyr::filter(CN_stat_veg_month , grepl("^.*:G.*:G", full_compar))
M_CN_stat_veg_month <- dplyr::filter(CN_stat_veg_month , grepl("^.*:M.*:M", full_compar))
MG_CN_stat_veg_month <- dplyr::filter(CN_stat_veg_month , grepl("^.*:T.*:T", full_compar)) 

# merge relevant comparisons to one dataframe
CN_stat_veg_month_rel <- G_CN_stat_veg_month %>%
  full_join(M_CN_stat_veg_month, by = c("term", "group1", "group2", "null.value", "estimate", "conf.low", "conf.high", "p.adj", "p.adj.signif", "full_compar")) 

CN_stat_veg_month_rel <- CN_stat_veg_month_rel %>%
  full_join(MG_CN_stat_veg_month, by = c("term", "group1", "group2", "null.value", "estimate", "conf.low", "conf.high", "p.adj", "p.adj.signif", "full_compar")) 

# make a column with only vegetation so that this dataset matches with the PLFA data
CN_stat_veg_month_rel <- separate(data = CN_stat_veg_month_rel, col = group1, into = c("group1", "veg_abrev"), sep = "\\:")


CN_stat_veg_month_rel$vegetation <- factor(CN_stat_veg_month_rel$veg_abrev, levels = c("G", "T", "M"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite"))

#remove vegetation from group2
CN_stat_veg_month_rel$group2<- gsub(':G','',CN_stat_veg_month_rel$group2)
CN_stat_veg_month_rel$group2<- gsub(':M','',CN_stat_veg_month_rel$group2)
CN_stat_veg_month_rel$group2<- gsub(':T','',CN_stat_veg_month_rel$group2)


#manually add y-position
CN_stat_veg_month_rel <- CN_stat_veg_month_rel %>%
 mutate(y.position = c(14, 15, 16, 17, 12, 11, 13,
                       14, 15, 16, 17, 12, 13,
                       15, 16, 17, 12, 13, 14))

# add p-values to plot
CN_plot + stat_pvalue_manual(CN_stat_veg_month_rel)


```