---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Differential Abundance Analysis
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 12pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 6,
  fig.width = 8,
  class.source="bg-warning",
  class.output="bg-success"
)

```

# **Import qiime formatted data**
  - https://blog.codyglickman.com/2018/10/qiime2-to-phyloseq.html

```{r import_data}
library(phyloseq)

biom_data_raw <- import_biom(BIOMfilename = "Bacteria/bacteria_taxa_table_raw.biom", refseqfilename = "Bacteria/bacteria-dna-sequences-rare.fasta")

mapping_file <- import_qiime_sample_data(mapfilename = "Bacteria/CORRECTED_metadata.tsv")


# Merge the OTU and mapping data into a phyloseq object
phylo_raw <- merge_phyloseq(biom_data_raw, mapping_file)
#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```
# **remove controls + contaminants**

```{r clean_data}
library(decontam)

# threshold 0.5, identifies 9 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)

#prune the contaminated taxa
phylo_rm_contaminat <- prune_taxa(!contamdf.prev05$contaminant, phylo_raw)
phylo_rm_contaminat #after

#remove any left over controls so they dont impact normalization
phylo_rm_contaminat_rm_cntrl = subset_samples(phylo_rm_contaminat, sample.id != "CONTROL1-S1" & sample.id != "CONTROL2-S79" & sample.id != "CONTROL3-S109")


## remove unknowns and archaea, keep only bacteria
bac <- subset_taxa(phylo_rm_contaminat_rm_cntrl, Kingdom == "d__Bacteria")
phylo_rm_archaea <- prune_taxa(c(taxa_names(bac)), phylo_rm_contaminat_rm_cntrl) 

```

# **Differential Abundance Analysis**
  - https://microbiome.github.io/OMA/differential-abundance.html
  - https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html 
  - https://doi.org/10.1038/s41467-020-17041-7
  
  -FOLLOWING THIS TUTORIAL: https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html 
  
  - https://www.yanh.org/2021/01/01/microbiome-r/#differential-abundance-analysis 
  
  
```{r DAA_with_ANCOMBC}
library(scater)
library(ANCOMBC)
library(tidyverse)
library(DT)
library(phyloseq)
library(microbiome)
library(mia)


tse = mia::makeTreeSummarizedExperimentFromPhyloseq(phylo_rm_archaea)

set.seed(123)
# It should be noted that we have set the number of bootstrap samples (B) equal 
# to 10 in the 'trend_control' function for computational expediency. 
# However, it is recommended that users utilize the default value of B, 
# which is 100, or larger values for optimal performance.
output = ancombc2(data = tse, assay_name = "counts", tax_level = "Class",
                  fix_formula = "vegetation", rand_formula = NULL,
                  p_adj_method = "holm", pseudo_sens = TRUE,
                  prv_cut = 0.10, lib_cut = 1000, s0_perc = 0.05,
                  group = "vegetation", struc_zero = TRUE, neg_lb = TRUE,
                  alpha = 0.05, n_cl = 2, verbose = TRUE,
                  global = TRUE, pairwise = TRUE, dunnet = TRUE, trend = TRUE,
                  iter_control = list(tol = 1e-2, max_iter = 20, 
                                      verbose = TRUE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = lme4::lmerControl(),
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
                  trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                              nrow = 2, 
                                                              byrow = TRUE),
                                                       matrix(c(-1, 0, 1, -1),
                                                              nrow = 2, 
                                                              byrow = TRUE),
                                                       matrix(c(1, 0, 1, -1),
                                                              nrow = 2, 
                                                              byrow = TRUE)),
                                       node = list(2, 2, 1),
                                       solver = "ECOS",
                                       B = 10))

```

```{r visualize_ANCOMBC2}

## From tutorial: "5.5 ANCOM-BC2 multiple pairwise comparisons"

res_pair = output$res_pair %>%
    mutate_if(is.numeric, function(x) round(x, 2))
res_pair[1:21, ] %>%
    datatable(caption = "ANCOM-BC2 Multiple Pairwise Comparisons")

## From tutorial "4.6 ANCOM-BC2 multiple pairwise comparisons"

res_pair = output$res_pair

df_fig_pair1 = res_pair %>%
    dplyr::filter(diff_vegetationMesquite == 1 |
                      diff_vegetationMesquite_grass == 1 | 
                      diff_vegetationMesquite_grass_vegetationMesquite == 1) %>%
    dplyr::mutate(M = ifelse(diff_vegetationMesquite == 1, 
                                round(lfc_vegetationMesquite, 2), 0),
                  MG = ifelse(diff_vegetationMesquite_grass == 1, 
                                round(lfc_vegetationMesquite_grass, 2), 0),
                  MGM = ifelse(diff_vegetationMesquite_grass_vegetationMesquite == 1, 
                                round(lfc_vegetationMesquite_grass_vegetationMesquite, 2), 0)) %>%
    tidyr::pivot_longer(cols = M:MGM, 
                        names_to = "group", values_to = "value") %>%
    dplyr::arrange(taxon)

df_fig_pair2 = res_pair %>%
    dplyr::filter(diff_vegetationMesquite == 1 |
                      diff_vegetationMesquite_grass == 1 | 
                      diff_vegetationMesquite_grass_vegetationMesquite == 1) %>%
    dplyr::mutate(M = ifelse(passed_ss_vegetationMesquite == 1 & diff_vegetationMesquite == 1, 
                                "aquamarine3", "black"),
                  MG = ifelse(passed_ss_vegetationMesquite_grass == 1 & diff_vegetationMesquite_grass == 1, 
                                "aquamarine3", "black"),
                  MGM = ifelse(passed_ss_vegetationMesquite_grass_vegetationMesquite == 1 & diff_vegetationMesquite_grass_vegetationMesquite == 1, 
                                "aquamarine3", "black")) %>%
    tidyr::pivot_longer(cols = M:MGM, 
                        names_to = "group", values_to = "color") %>%
    dplyr::arrange(taxon)

df_fig_pair = df_fig_pair1 %>%
    dplyr::left_join(df_fig_pair2, by = c("taxon", "group"))

df_fig_pair$group = recode(df_fig_pair$group, 
                          `M` = "Mesquite - Grass",
                          `MG` = "Mesquite_grass - Grass",
                          `MGM` = "Mesquite_grass - Mesquite")
df_fig_pair$group = factor(df_fig_pair$group, 
                          levels = c("Mesquite - Grass",
                                     "Mesquite_grass - Grass", 
                                     "Mesquite_grass - Mesquite"))

lo = floor(min(df_fig_pair$value))
up = ceiling(max(df_fig_pair$value))
mid = (lo + up)/2
fig_pair = df_fig_pair %>%
    ggplot(aes(x = group, y = taxon, fill = value)) + 
    geom_tile(color = "black") +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                         na.value = "white", midpoint = 0, limit = c(lo, up),
                         name = NULL) +
    geom_text(aes(group, taxon, label = value, color = color), size = 4) +
    scale_color_identity(guide = FALSE) +
    labs(x = NULL, y = NULL, title = "Pairwise log fold changes") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
fig_pair

```