
---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Fungal Modeling
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 15pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 6,
  fig.width = 9,
  class.source="bg-warning",
  class.output="bg-success"
)

```

# **Import formatted data**

```{r import_data}

library(phyloseq)
library(dplyr)
library(tidyverse)
library(vegan)


load("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/fungi_dada2_data.RData") 
#contains taxa and otu table


#import metadata
sam <- read.csv("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/Fungi/fungi_oct_28_metadata.csv", header = TRUE) 
rownames(sam) <- sam$sample.id

#add month_veg row to data
sam$month_veg = paste(sam$month, sam$vegetation, sep="-")

#adjust sample data labels
sam$Vegetation <- factor(sam$vegetation, levels = c("Grass", "Mesquite_grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 

sam$Month <- factor(sam$month, levels = c("Oct", "Jan", "Mar", "May", "Jul"), 
                  labels = c("October", "January", "March", "May", "July"))

#compile data into phyloseq object
phylo_raw <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), 
               sample_data(sam), 
               tax_table(taxa))


dna <- Biostrings::DNAStringSet(taxa_names(phylo_raw))
names(dna) <- taxa_names(phylo_raw)
phylo_raw <- merge_phyloseq(phylo_raw, dna)
taxa_names(phylo_raw) <- paste0("ASV", seq(ntaxa(phylo_raw)))
phylo_raw

#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```

# **remove controls + contaminants**

```{r decontam}
library(decontam)

# threshold 0.5, identifies 0 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)


#remove any left over controls so they don't impact rarefy
#remove sample 129 and 93 as it had very low reads after filtering, don't want them to impact rarefy
phylo_rm_cntrl = subset_samples(phylo_raw, sample.id != "Control1" & sample.id != "ControlL2")

# #get relative abundance
 library(microbiome)
 phylo_rm_cntrl <- phylo_rm_cntrl %>% 
        microbiome::transform(transform = "compositional")
```
```{r}
library(microbiome)
library(ggplot2)
library(dplyr)
library(IRanges)
library(dplyr)

# Get sample metadata
dfs <- meta(phylo_rm_cntrl) 


library(lme4)
library(lmerTest)
library(sjPlot)
# Paired comparison
out1 <- lmer(Fungal._Biomass_Percent ~ soil_pH + (1| plot), data = dfs)
tab_model(out1)


out2 <- lmer(Fungal._Biomass_Percent ~ carbon_to_nitrogen_ratio + (1| plot), data = dfs)
AIC(out2) #1039.51
tab_model(out2)

out3 <- lmer(Fungal._Biomass_Percent ~ avg_monthly_air_temp_C + (1| plot), data = dfs)
AIC(out3) #964.2789
tab_model(out3)



out4 <- lmer(Fungal._Biomass_Percent ~ average_montlhy_humidity + (1| plot), data = dfs)
AIC(out4) #981.3405
tab_model(out4)


out5 <- lmer(Fungal._Biomass_Percent ~ avg_monthly_ppt + (1| plot), data = dfs)
AIC(out5) #1045.317
tab_model(out5)


out6 <- lmer(Fungal._Biomass_Percent ~ average_montlhy_humidity*avg_monthly_air_temp_C + (1| plot), data = dfs)
tab_model(out6)

out7 <- lmer(Fungal._Biomass_Percent ~ average_montlhy_humidity + avg_monthly_air_temp_C + soil_pH + (1| plot), data = dfs)
tab_model(out7)

out8 <- lmer(Fungal._Biomass_Percent ~ average_montlhy_humidity + avg_monthly_air_temp_C + soil_pH + carbon_to_nitrogen_ratio + (1| plot), data = dfs)
tab_model(out8)



### model 6 seems to be the best, need to check assumptions ###
plot(out6)
qqnorm(resid(out6))
qqline(resid(out6), col = "red") 


#assumptions not met, need to transform

out6_log <- lmer(log(bacterial_biomass_percentage) ~ (average_montlhy_humidity)* (avg_monthly_air_temp_C) + (1| plot), data = dfs)
tab_model(out6_log)

plot(out6_log)
qqnorm(resid(out6_log))
qqline(resid(out6_log), col = "red") 

```
