---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Fungal Differential Abundance Analysis
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 15pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 6,
  fig.width = 9,
  class.source="bg-warning",
  class.output="bg-success"
)

```

# **Import formatted data**

```{r import_data}

library(phyloseq)
library(dplyr)
library(tidyverse)
library(vegan)


load("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/fungi_dada2_data.RData") 
#contains taxa and otu table


#import metadata
sam <- read.csv("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/Fungi/fungi_oct_28_metadata.csv", header = TRUE) 
rownames(sam) <- sam$sample.id

#add month_veg row to data
sam$month_veg = paste(sam$month, sam$vegetation, sep="-")

#adjust sample data labels
sam$Vegetation <- factor(sam$vegetation, levels = c("Grass", "Mesquite_grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 

sam$Month <- factor(sam$month, levels = c("Oct", "Jan", "Mar", "May", "Jul"), 
                  labels = c("October", "January", "March", "May", "July"))

#compile data into phyloseq object
phylo_raw <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), 
               sample_data(sam), 
               tax_table(taxa))


dna <- Biostrings::DNAStringSet(taxa_names(phylo_raw))
names(dna) <- taxa_names(phylo_raw)
phylo_raw <- merge_phyloseq(phylo_raw, dna)
taxa_names(phylo_raw) <- paste0("ASV", seq(ntaxa(phylo_raw)))
phylo_raw

#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```

# **remove controls + contaminants**

```{r decontam}
library(decontam)

# threshold 0.5, identifies 0 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)


#remove any left over controls so they don't impact rarefy
#remove sample 129 and 93 as it had very low reads after filtering, don't want them to impact rarefy
phylo_rm_cntrl = subset_samples(phylo_raw, sample.id != "Control1" & sample.id != "ControlL2")

```

```{r DAA_with_ANCOMBC}
library(scater)
library(ANCOMBC)
library(tidyverse)
library(DT)
library(phyloseq)
library(microbiome)
library(mia)


tse = mia::makeTreeSummarizedExperimentFromPhyloseq(phylo_rm_cntrl)

set.seed(123)
# It should be noted that we have set the number of bootstrap samples (B) equal 
# to 10 in the 'trend_control' function for computational expediency. 
# However, it is recommended that users utilize the default value of B, 
# which is 100, or larger values for optimal performance.
output = ancombc2(data = tse, assay_name = "counts", tax_level = "Order",
                  fix_formula = "vegetation", rand_formula = NULL,
                  p_adj_method = "holm", pseudo_sens = TRUE,
                  prv_cut = 0.10, lib_cut = 1000, s0_perc = 0.05,
                  group = "vegetation", struc_zero = TRUE, neg_lb = TRUE,
                  alpha = 0.05, n_cl = 2, verbose = TRUE,
                  global = TRUE, pairwise = TRUE, dunnet = TRUE, trend = TRUE,
                  iter_control = list(tol = 1e-2, max_iter = 20, 
                                      verbose = TRUE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  lme_control = lme4::lmerControl(),
                  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
                  trend_control = list(contrast = list(matrix(c(1, 0, -1, 1),
                                                              nrow = 2, 
                                                              byrow = TRUE),
                                                       matrix(c(-1, 0, 1, -1),
                                                              nrow = 2, 
                                                              byrow = TRUE),
                                                       matrix(c(1, 0, 1, -1),
                                                              nrow = 2, 
                                                              byrow = TRUE)),
                                       node = list(2, 2, 1),
                                       solver = "ECOS",
                                       B = 10))

```

```{r visualize_ANCOMBC2}

## From tutorial: "4.3 Structural zeros (taxon presence/absence)"
tab_zero = output$zero_ind
tab_zero %>%
    datatable(caption = "The detection of structural zeros")

## From tutorial: "5.5 ANCOM-BC2 multiple pairwise comparisons"

res_pair = output$res_pair %>%
    mutate_if(is.numeric, function(x) round(x, 2))
res_pair[1:122, ] %>%
    datatable(caption = "ANCOM-BC2 Multiple Pairwise Comparisons")

## From tutorial: "5.4 ANCOM-BC2 global test"
res_global = output$res_global %>%
    mutate_if(is.numeric, function(x) round(x, 2))
res_global[1:6, ] %>%
    datatable(caption = "ANCOM-BC2 Global Test")

## From tutorial: "5.6 ANCOM-BC2 Dunnett’s type of test"
res_dunn = output$res_dunn %>%
    mutate_if(is.numeric, function(x) round(x, 2))
res_dunn[1:122, ] %>%
    datatable(caption = "ANCOM-BC2 Dunnett's Type of Test")

## From tutorial: "5.7 ANCOM-BC2 pattern analysis"
res_trend = output$res_trend %>%
    mutate_if(is.numeric, function(x) round(x, 2))
res_trend[1:121, ] %>%
    datatable(caption = "ANCOM-BC2 Pattern Analysis")

## From tutorial: "6. Bias-corrected log abundances"
bias_correct_log_table = output$bias_correct_log_table
# By default, ANCOM-BC2 does not add pseudo-counts to zero counts, which can 
# result in NAs in the bias-corrected log abundances. Users have the option to 
# either leave the NAs as they are or replace them with zeros. 
# This replacement is equivalent to adding pseudo-counts of ones to the zero counts. 
bias_correct_log_table[is.na(bias_correct_log_table)] = 0
# Show the first 6 samples
round(bias_correct_log_table[, 1:121], 2) %>% 
  datatable(caption = "Bias-corrected log abundances")


## From tutorial "4.6 ANCOM-BC2 multiple pairwise comparisons"

# The ANCOM-BC2 methodology for multiple pairwise comparisons is designed to identify taxa that exhibit differential abundance between any two groups within a set of three or more experimental groups, all while maintaining control over the mdFDR.
# 
# For instance, in our analysis focusing on the categories “lean”, “overweight”, and “obese”, the output provides: 1) log fold changes, 2) standard errors, 3) test statistics, 4) p-values, 5) adjusted p-values, 6) indicators denoting whether the taxon is differentially abundant (TRUE) or not (FALSE), and 7) indicators denoting whether the taxon passed the sensitivity analysis (TRUE) or not (FALSE).
# 
# In the subsequent heatmap, each cell represents a log fold-change (in natural log) value. Entries highlighted in color #e1bc29 have successfully passed the sensitivity analysis for pseudo-count addition.

res_pair = output$res_pair

df_fig_pair1 = res_pair %>%
    dplyr::filter(diff_vegetationMesquite == 1 |
                      diff_vegetationMesquite_grass == 1 | 
                      diff_vegetationMesquite_grass_vegetationMesquite == 1) %>%
    dplyr::mutate(M = ifelse(diff_vegetationMesquite == 1, 
                                round(lfc_vegetationMesquite, 2), 0),
                  MG = ifelse(diff_vegetationMesquite_grass == 1, 
                                round(lfc_vegetationMesquite_grass, 2), 0),
                  MGM = ifelse(diff_vegetationMesquite_grass_vegetationMesquite == 1, 
                                round(lfc_vegetationMesquite_grass_vegetationMesquite, 2), 0)) %>%
    tidyr::pivot_longer(cols = M:MGM, 
                        names_to = "group", values_to = "value") %>%
    dplyr::arrange(taxon)

df_fig_pair2 = res_pair %>%
    dplyr::filter(diff_vegetationMesquite == 1 |
                      diff_vegetationMesquite_grass == 1 | 
                      diff_vegetationMesquite_grass_vegetationMesquite == 1) %>%
    dplyr::mutate(M = ifelse(passed_ss_vegetationMesquite == 1 & diff_vegetationMesquite == 1, 
                                "#e1bc29", "black"),
                  MG = ifelse(passed_ss_vegetationMesquite_grass == 1 & diff_vegetationMesquite_grass == 1, 
                                "#e1bc29", "black"),
                  MGM = ifelse(passed_ss_vegetationMesquite_grass_vegetationMesquite == 1 & diff_vegetationMesquite_grass_vegetationMesquite == 1, 
                                "#e1bc29", "black")) %>%
    tidyr::pivot_longer(cols = M:MGM, 
                        names_to = "group", values_to = "color") %>%
    dplyr::arrange(taxon)

df_fig_pair = df_fig_pair1 %>%
    dplyr::left_join(df_fig_pair2, by = c("taxon", "group"))

df_fig_pair$group = recode(df_fig_pair$group, 
                          `M` = "Mesquite - Grass",
                          `MG` = "Ecotone - Grass",
                          `MGM` = "Ecotone - Mesquite")
df_fig_pair$group = factor(df_fig_pair$group, 
                          levels = c("Mesquite - Grass",
                                     "Ecotone - Grass", 
                                     "Ecotone - Mesquite"))

lo = floor(min(df_fig_pair$value))
up = ceiling(max(df_fig_pair$value))
mid = (lo + up)/2
fig_pair = df_fig_pair %>%
    ggplot(aes(x = group, y = taxon, fill = value)) + 
    geom_tile(color = "black") +
    scale_fill_gradient2(low = "#c1292e", high = "#679436", mid = "white", 
                         na.value = "white", midpoint = 0, limit = c(lo, up),
                         name = NULL) +
    geom_text(aes(group, taxon, label = value, color = color), size = 4) +
    scale_color_identity(guide = FALSE) +
    labs(x = NULL, y = NULL, title = "Pairwise log fold changes") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
fig_pair

```

```{r session_info}
library(devtools)
session_info()
```