---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Fungal Richness and Diversity
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 12pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 4,
  fig.width = 6,
  class.source="bg-warning",
  class.output="bg-success"
)

```

# **Import formatted data**

```{r import_data}

library(phyloseq)
library(dplyr)
library(tidyverse)
library(vegan)


load("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/fungi_dada2_data.RData") 
#contains taxa and otu table


#import metadata
sam <- read.csv("~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/Fungi/fungi_oct_28_metadata.csv", header = TRUE) 
rownames(sam) <- sam$sample.id

#add month_veg row to data
sam$month_veg = paste(sam$month, sam$vegetation, sep="-")

#adjust sample data labels
sam$Vegetation <- factor(sam$vegetation, levels = c("Grass", "Mesquite_grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 

sam$Month <- factor(sam$month, levels = c("Oct", "Jan", "Mar", "May", "Jul"), 
                  labels = c("October", "January", "March", "May", "July"))

#compile data into phyloseq object
phylo_raw <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), 
               sample_data(sam), 
               tax_table(taxa))


dna <- Biostrings::DNAStringSet(taxa_names(phylo_raw))
names(dna) <- taxa_names(phylo_raw)
phylo_raw <- merge_phyloseq(phylo_raw, dna)
taxa_names(phylo_raw) <- paste0("ASV", seq(ntaxa(phylo_raw)))
phylo_raw

#Add names to biom table and check phyloseq objects
colnames(tax_table(phylo_raw))= c("Kingdom","Phylum","Class","Order","Family","Genus", "Species")
```

# **remove controls + contaminants**

```{r decontam}
library(decontam)

# threshold 0.5, identifies 0 contaminants
contamdf.prev05 <- isContaminant(phylo_raw, method="prevalence", neg="neg", threshold=0.5)
table(contamdf.prev05$contaminant)


#remove any left over controls so they don't impact rarefy
#remove sample 129 and 93 as it had very low reads after filtering, don't want them to impact rarefy
phylo_rm_cntrl = subset_samples(phylo_raw, sample.id != "Control1" & sample.id != "ControlL2")

```

```{r richness}
richness <- estimate_richness(phylo_rm_cntrl)

#Shannon
anova.sh.veg = aov(richness$ACE ~ sample_data(phylo_rm_cntrl)$Vegetation*sample_data(phylo_rm_cntrl)$Month)
summary(anova.sh.veg)

#post hoc
tukey.sh <- TukeyHSD(anova.sh.veg)
tukey.sh$`sample_data(phylo_rm_cntrl)$Month`

tukey.sh 


#plot
ACE <- plot_richness(phylo_rm_cntrl, x = "Month", measures = c("ACE"))
ACE_box <- ACE + geom_boxplot()
ACE_box

```

# Model richness factors

```{r}

library(tibble)
library(dplyr)
library(phylosmith)


# Extract abundance matrix from the phyloseq object
OTU1 = as(otu_table(phylo_rm_cntrl), "matrix")
# transpose if necessary
if(taxa_are_rows(phylo_rm_cntrl)){OTU1 <- t(OTU1)}
# Coerce to data.frame
OTUdf = as.data.frame(OTU1)


#extract taxa table
taxa = as(tax_table(phylo_rm_cntrl), "matrix")
taxadf = as.data.frame(taxa)
taxadf <- tibble::rownames_to_column(taxadf, "sample.id")

# transpose 

#add metadata to OTU table
OTUdf2 <- tibble::rownames_to_column(OTUdf, "sample.id")
OTUdf_merge <- merge(sam, OTUdf2, by.y= "sample.id")


richness1 <- tibble::rownames_to_column(richness, "sample.id")
richness1$sample.id <- gsub("X", "", paste(richness1$sample.id))

df_merge_rich <- merge(richness1, OTUdf_merge, by.y= "sample.id")


### ANCOVA ###

# response: richness
# predictor: vegetation, proximity? 

library(lme4)
library(lmerTest)
library(sjPlot)


m1 <- lmer(Shannon ~ Vegetation + (1| proximity1), data = df_merge_rich)
AIC(m1)

m2 <- lmer(Shannon ~ Month + (1| proximity1), data = df_merge_rich)
AIC(m2)

m3 <- lmer(Shannon ~ Month*Vegetation + (1| proximity1), data = df_merge_rich)
AIC(m3)

m4 <- lmer(Shannon ~ Month + Vegetation + (1| proximity1), data = df_merge_rich)
AIC(m4)

m5 <- lmer(Shannon ~ Vegetation*avg_monthly_air_temp_C + (1| proximity1), data = df_merge_rich)
AIC(m5)

m6 <- lmer(Shannon ~ Vegetation*soil_pH + (1| proximity1), data = df_merge_rich)
AIC(m6)
summary(m6)
tab_model(m6)

m7 <- lmer(Shannon ~ Vegetation*carbon_to_nitrogen_ratio + (1| proximity1), data = df_merge_rich)
AIC(m7)

m8 <- lmer(Shannon ~ Vegetation*soil_temperature_C + (1| proximity1), data = df_merge_rich)
AIC(m8)

m9 <- lmer(Shannon ~ Vegetation*average_montlhy_humidity + (1| proximity1), data = df_merge_rich)
AIC(m9)

m10 <- lmer(Shannon ~ Vegetation*avg_monthly_ppt + (1| proximity1), data = df_merge_rich)
AIC(m10)

m11 <- lmer(Shannon ~ Month*avg_monthly_air_temp_C + (1| proximity1), data = df_merge_rich)
AIC(m11)

m12 <- lmer(Shannon ~ Month*soil_pH + (1| proximity1), data = df_merge_rich)
AIC(m12)

m13 <- lmer(Shannon ~ Month*carbon_to_nitrogen_ratio + (1| proximity1), data = df_merge_rich)
AIC(m13)

m14 <- lmer(Shannon ~ Month*soil_temperature_C + (1| proximity1), data = df_merge_rich)
AIC(m14)

m15 <- lmer(Shannon ~ Month*average_montlhy_humidity + (1| proximity1), data = df_merge_rich)
AIC(m15)

m16 <- lmer(Shannon ~ Month*avg_monthly_ppt + (1| proximity1), data = df_merge_rich)
AIC(m16)

```



```{r phylogenic_diversity}
# 
# library(picante)
# otu_table <- as.data.frame(phylo_rm_cntrl@otu_table)
# metadata_table <- as.data.frame(phylo_rm_cntrl@sam_data)
# 
# df.pd <- pd(t(otu_table), treefile_p1, include.root=F) # t(ou_table) transposes the table for use in picante and the tre file comes from the first code chunck we used to read tree file (see making a phyloseq object section).
# 
# 
# datatable(df.pd)
# 
```

