---
title: '<span style = ''font-size:14pt;''>**Microbial Communities in the changing vegetation of the Chihuahuan Desert 
**</span>'
subtitle: '<span style = ''font-size:12pt;''> Leaf Litter Decompostion
</span>'
author: "Emily Embury"
date: "`r Sys.Date()`"
output: html_document
---
<style type="text/css">
/* Whole document: */ 
body{
  font-size: 12pt;
}
/* Headers */
h1{
  font-size: 15pt;
}
</style>

---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,              
  warning = FALSE,       
  message = FALSE,  
  cache = FALSE,        
  fig.align = "center", 
  fig.height = 6,
  fig.width = 9,
  class.source="bg-warning",
  class.output="bg-success"
)

```


# **Litter Decomposition**

"Not too important for this report, but for your thesis, write days instead of collection period in the x axis." -- from Adriana

Mass loss from litter bags


Collection Periods:

  - a = 87 days of decomposition
  - b = 145 days of decomposition
  - c = 207 days of decomposition
  - d = 269 days of decomposition

```{r import_data}
litter_seived <- read.csv("Raw_data/litter/Litter_bags_seived_rm_open.csv")

litter_seived$Vegetation <- factor(litter_seived$Vegetation, levels = c("Grass", "Mesquite-Grass", "Mesquite"), 
                  labels = c("Grass", "Grass-Mesquite", "Mesquite")) 
```

```{r}

library(ggplot2)
library(ggbreak) 

#get standard deviation for error bars
library(Rmisc)
litter_sum_seived <- summarySE(litter_seived, measurevar = "Biomass_change", groupvars=c("Decomp_days","Vegetation"))



litter_plot_seived <- ggplot(litter_sum_seived, aes(x= Decomp_days, y = Biomass_change, group = Vegetation))+
  geom_line(aes(color=Vegetation))+
  geom_point()+
  theme_linedraw()+
  theme(plot.title = element_text(face = "bold", hjust = 0.5))+
  xlab("Days") + # change x axis label
  ylab("Average Change in Biomass (g)")+ # change y axis label
  ggtitle("Leaf Litter Mass Lost in Different Vegetation Types")+
  scale_color_manual(values=c("Mesquite" ="#c1292e", "Grass-Mesquite" = "#e1bc29", "Grass" = "#679436"))+
  geom_errorbar(aes(ymin=Biomass_change-se, ymax=Biomass_change+se, color = Vegetation), width=4) 
  


litter_plot_seived

ggsave(file="~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/images/leaf_litter.png", device = png, plot=litter_plot_seived, width=7, height=5)
```
#**stats**
```{r}

library(tidyverse)

#anova
ll_aov <- aov(Biomass_change ~ Vegetation*Collection_period, data = litter_seived)
summary(ll_aov)

ll_aov_summary <- capture.output(summary(ll_aov)) 

write.table(ll_aov_summary, file = "~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/leaf_litter_aov.txt", sep = ",", quote = FALSE, row.names = T)


#check anova assumptions
par(mfrow = c(1,2)) #puts the plots next to each other
qqnorm(ll_aov $residuals) #normal q-q plot, tests normality
qqline(ll_aov $residuals, col = "red") #line of fit on q-q plot
plot(ll_aov $fitted.values, ll_aov $residuals, main = "Residuals vs Fitted", xlab = "Fitted Values", 
     ylab = "Residuals") #residuals vs. fitted, test variance
abline(h=0, col = "red") 


# tukeyHSD post-hoc
ll_tuk <- TukeyHSD(ll_aov)

#view post hoc results

# decomp x vegetation
tuk_veg <- ll_tuk$Vegetation
write.table(tuk_veg, file = "~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/leaf_litter_tukey_veg.txt", sep = ",", quote = FALSE, row.names = T)

# decomp x collection period
col_perd <- ll_tuk$Collection_period
write.table(col_perd, file = "~/Desktop/Master_Data/Masters_R/NMSU_Soil_Microbial_Analysis/leaf_litter_tukey_coll_period.txt", sep = ",", quote = FALSE, row.names = T)

# decomp x vegetation*veg
tuk_cp_veg <- as.data.frame(ll_tuk$`Vegetation:Collection_period`)

tuk_cp_veg %>%
filter(`p adj` < .05)
```

```{r session_info}
library(devtools)
session_info()
```
